name: authservice-standard
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: authservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5429:5432"
    volumes:
      - authservice_postgres_data:/var/lib/postgresql/data

volumes:
  authservice_postgres_data: