name: productservice-standard
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: productservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5428:5432"
    volumes:
      - productservice_postgres_data:/var/lib/postgresql/data

volumes:
  productservice_postgres_data: