spring:
  application:
    name: productservice

  datasource:
    url: jdbc:postgresql://localhost:5431/productservice
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5431/productservice
    user: admin
    password: admin
    schemas: public
    create-schemas: true
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: true

server:
  port: 8083

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

logging:
  level:
    org:
      flywaydb: DEBUG

      #springframework:
      #  security: TRACE