name: orderservice-standard
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: orderservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5427:5432"
    volumes:
      - orderservice_postgres_data:/var/lib/postgresql/data

volumes:
  orderservice_postgres_data: