spring:
  application:
    name: authservice

  datasource:
    url: jdbc:postgresql://localhost:5430/authservice
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5430/authservice
    user: admin
    password: admin
    schemas: public
    create-schemas: true
    enabled: true
    baseline-version: 0
    validate-on-migrate: false
    locations: classpath:db/migration
    clean-disabled: true

server:
  port: 8081

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000

logging:
  level:
    org:
      flywaydb: DEBUG

admin:
  username: admin
  password: admin