name: orderservice-ecs
services:
  postgres:
    image: postgres
    container_name: orderservice-ecs
    environment:
      POSTGRES_DB: orderservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - orderservice_postgres_data:/var/lib/postgresql/data

volumes:
  orderservice_postgres_data: